title: Paul E. Plonski
email: paul.plonski@swarthmore.edu
description: >-
  Research Fellow and Part-time Visiting Assistant Professor of Psychology at Swarthmore College.
url: "https://www.paulplonski.com"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"

# Site Author
author:
  name             : "Paul E. Plonski"
  avatar           : "https://images.unsplash.com/photo-1448375240586-882707db888b?w=400&q=80"
  bio              : "Research Fellow & Part-time Visiting Assistant Professor of Psychology, Swarthmore College."
  location         : "Swarthmore, PA"
  email            : "paul.plonski@swarthmore.edu"
  links:
    - label: "CV"
      icon: "fas fa-fw fa-file-alt"
      url: "/assets/files/plonski_CV.pdf"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=BTRt_w0AAAAJ"
    - label: "OSF"
      icon: "fas fa-fw fa-flask"
      url: "https://osf.io/user/c9pgz"
    - label: "More to come"
      icon: "fas fa-fw fa-share-alt"
      url: "#"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      share: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Reading Files
include:
  - _pages

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - "*.gem"
  - vendor/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-WF475Z8EDW"
    anonymize_ip: false